name: acceptance

on:
  pull_request:
    types: [ opened, synchronize ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: single-acceptance-job-per-repo

env:
  HATCH_VERBOSE: "2"
  HATCH_VERSION: "1.16.5"

jobs:
  integration:
    if: github.event_name == 'pull_request'
    environment: runtime
    runs-on: larger
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.14'

      - name: Install hatch
        run: pip install "hatch==${HATCH_VERSION}"

      - name: Run integration tests
        uses: databrickslabs/sandbox/acceptance@acceptance/v0.4.2
        with:
          vault_uri: ${{ secrets.VAULT_URI }}
          timeout: 45m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
